theme: jekyll-theme-minimal
title: CIT 281 - Project 5
description: I gained experience working with classes, including class constructors and methods, interpreting existing code to design a new class, including constructor and methods, working with code modules, executing and debugging Node.js code using VSCode, including module breakpoints, working with Array map() and forEach() methods, working with the concept of a gaming loop, and working with objects and arrays.
